### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by AngelCasillas01** [vYuri/Refke#1]
Maybe a rank can be added to this plugin, livestreamer with the green star, with the permission of /broadcast, /slap, etc

**Comment by vYuri** [comment]
This is really good idea, but the plugin is in Beta, we can add this in the nex week :') Thanks

**Comment by vYuri** [comment]
Reopened, working on this.

**Comment by javipepe** [comment]
May I ask why a livestreamer should have access to /slap or /broadcast?

**Comment by AngelCasillas01** [comment]
Livestreamer, /Broadcast for share links of their lives, slap i have say it randomly, sorry

**Comment by javipepe** [comment]
Sorry for the error. Reopening :)

**Comment by vYuri** [comment]
Command /broadcast added, we gonna see the permissions.

**Comment by AngelCasillas01** [comment]
@vYuri con los codigos que te pase o los hiciste tu?

**Comment by vYuri** [comment]
Los hice yo, igual gracias por intentar colaborar! :') @AngelCasillas01

**Comment by AngelCasillas01** [comment]
@vYuri oki
