### ISSUE TITLE
Que paso con el proyecto?

### ISSUE THREAD

**Issue by TiTo-418** [vYuri/Refke#15]

**Comment by vYuri** [comment]
Aun se esta programando, por lo tanto en algún momento saldrá la versión final :')

**Comment by TiTo-418** [comment]
Puedo probarlo?

**Comment by TiTo-418** [comment]
O como se compila?

**Comment by vYuri** [comment]
Por ahora no te recomendaría hacer pruebas, espera a una release a una compi.
