### ISSUE TITLE
[SUG] Add /mute

### ISSUE THREAD

**Issue by Tiwert** [vYuri/Refke#2]
Well, my idea is add /mute, in the rank mod, ref, and admin, i'll add more sugs here :') Thanks for the great idea.

**Comment by vYuri** [comment]
we will add the command /mute, vixo1 talk about this, alright thanks for the great idea.

**Comment by vYuri** [comment]
Reopened, working on this.

**Comment by javipepe** [comment]
This will be finished soon. Already stated it in the last commit.

**Comment by javipepe** [comment]
Deployed in commit <a href="https://github.com/vYuri/Refke/commit/a668442638db2aee0ddea0de178b6c94b67883bd">a668442</a>.

Thanks for your concern :smile:
