### ISSUE TITLE
SUG Permissions and ranks!

### ISSUE THREAD

**Issue by AngelCasillas01** [vYuri/Refke#8]
Refs should have permission too the /cycle, /start, /end, /broadcast, /a
Livestreamers can /broadcast and /a 
Mods can all comands with an exeption of the /restart or /stop the server
Admins can all commands

Add a "Captain" Rank which captains from other teams that use the server forget to have op, these rank can has, /start, /end and /cancel, /cycle too

Add the * of all colours for make a seen of tourney winners on the server

Refs can get ref permissions with /referee or in short with /ref, an announce on chat should be able, EX: Player01 is now is a referee 

Livestreamers can get permissions with /livestream or /live, an announce on chat should be able, EX: Player01 is now a livestreamer

Captains can get permmisions with /captain or /cap, an announce can be on chat as well, EX: Player01 is now a captain

Mods can get mos with /moderate or /mod, an announce can be on chat as well, EX: Player01 is now a mod, 

Admins should get their permission with /admin or /ad, an announce can be on chat, EX: Player01 is now a Admin.

The star of the captain rank can be the same as the Senior Moderator on OCN, or can be de Junior Moderator, you can choose.

Thats all hopefully this help

**Comment by vYuri** [comment]
I think it's a good idea but what we just put the command "/ ready" for a captains, we gonna add things over time and thanks for the good ideas, greetings.

**Comment by vYuri** [comment]
PS: We are adding it to "*" and show in the chat 

EX: Player01 is now a mod.

**Comment by AngelCasillas01** [comment]
Oh, Nice idea wit the /ready, other thing, for /ready, try that when obs type /ready should be livestreamers or have ranks because people try to troll the cmmand, on team sizes, with no permissions

**Comment by vYuri** [comment]
@AngelCasillas01 It will be easy to add, thanks for the idea! hope you are aware of the changes we make and for future release!

**Comment by javipepe** [comment]
So basically in this idea you are suggesting:

 - Some permissions for each rank
 - The stars for each rank
 - Broadcast player promotions

If that's it:

 - I've looked into permissions and they are not as easy as they seem. Maybe we could try using another plugin as a dependency and you get to choose the perms you want. 

 - Stars are already started and an API I made should make it way easier. Said API that would contain addRank(Prefix, Name of rank, List<String> of players' name) and setRank(Player, Name of rank)

 - I'm not sure if this is a great idea, maybe send a message to the promoted and the promoted. And a message to the adminchat. Also I assume having op would automatically give you "admin", so there is no really a point behind /ad or /admin in my opinion.

My guess is that this is something already working on. Nevertheless, thanks for your ideas.

Cheers.

**Comment by vYuri** [comment]
@javipepe So far I have not discovered anything, I was researching about permissions, but I have not found anything good, I'll have to keep looking for the method, we are still working on it.

**Comment by AngelCasillas01** [comment]
@javipepe I'm sorry, but if you can addall that stuff, the plugin would be awesome! More than is it right now!

**Comment by felipufeliu** [comment]
What about if you make it so captains can do /team force?

**Comment by vYuri** [comment]
@felipufeliu  That is really good idea, i can add this, thanks for the idea!

**Comment by AngelCasillas01** [comment]
@felipufeliu @vYuri but set a limit, because some people abuse the command, only if you can, is a really good idea, but if the command is abused, maybe the plugin can colapse or bug it :(

**Comment by vYuri** [comment]
@AngelCasillas01 I think is good idea, only paste the command /team force and /ready for the captains.

**Comment by AngelCasillas01** [comment]
@vYuri k

**Comment by javipepe** [comment]
I think I'm leaving this to one issue as we've got two for the same thing. Referencing and closing this issue to #3 

Thanks for all the information and suggestions you made. Regards :)
